### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by seblyng** [seblj/foodie#1]
# Ideas

- Find an API of ingredients to integrate with, and add all of them to my database. Then have autocomplete when adding ingredients from those ingredients.
- Let users add ingredients not autocompleted, however, do not add those ingredients to the autocomplete for others

- Add description or something to recipe_ingredient
- Find a way to not add user specified ingredient to ingredients table.

# Functionality 

## TODO

- [ ] - Integrate with an API over names of dishes for autocompletion for example
- [x] - Have the dishes assigned to your profile
- [ ] - Have collections to group the dinners, and be able to share a collection with a friend
- [ ] - Get x random dishes
- [ ] - Head v Head fight for x amount of rounds where the winner is the dish you most want (completely random, inside a category etc)
- [ ] - Kitchen v Kitchen (Mexican v Italian for example).
- [ ] - If autocompletion succeeds, automatically categorize the food for if it is italian, comfort food for example (Must be editable)
- [ ] - Assign what you want to eat and merge the shopping lists for the different dishes where if you for example need half a cucumber for two dishes, you only get one cucumber instead of two in the shopping list.
- [x] - Browse through the dishes in the profile

### Way into the future if I ever get this far

- [ ] - Get suggestions on dinner from some database based on what you already have in your profile
- [ ] - Automatically create a dish based on whats in the fridge, and also find where you have to buy the least amount of food to avoid waste.
